Ask BSP for test execution environment
JetBrains/intellij-scala pull request #500
Opened 2020-02-14 17:11 UTC by tpasternak

When the project is imported from SBT, it is expected that the tests
executed with IntelliJ runners will behave exactly the same as if they
would be run by BSP Server. In order to achieve this, the runner must
download some critical environment parameters from BSP server via
jvmTestEnvironment, and use them to spawn child testing process. These
parameters are:

  - classpath
  - environment variables
  - working directory
  - JVM options

The place where the parameters are set is
`BspJvmEnvironmentProgramPatcher`. Unfortunately, the
JavaProgramPatchers are executed in the Event Dispatch Thread, so it
is forbidden to do a (always blocking) BSP call inside. In order to
overcome it, the BSP call is done in BspFetchTestEnvironmentTask,
which is executed on a pool thread before each test execution. The
environment is then saved via `putUserData`, so the patcher can read
it without blocking.

Another tricky thing here is mapping from IntelliJ module to BSP
target. On the other hand, the targetId is required to receive JVM
environment via BSP. Unfortunately, there may be more than one target that matches
the module, so in cases when it's impossible to unambiguously
determine which target is the right one, a popup is shown, so it's
possible to choose from a list of potential targets. The choice is
saved as a `BspFetchTestEnvironmentTask`'s setting.

This addresses https://youtrack.jetbrains.com/issue/SCL-16934

2020-02-14 18:19 UTC, jastice commented
Thank you! I'll handle this next week

2020-02-18 14:01 UTC, jastice requested changes
Thanks for the PR! As to the general approach, couldn't we just request the data on project import instead of before every test? Also we need to account for the server not supporting the requests used here at all. Maybe this needs some kind of `capabilities` addition in the protocol.

Also, please rebase onto idea201.x branch

2020-02-18 14:01 UTC, jastice commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchEnvironmentTaskInstaller.scala
> +class BspFetchEnvironmentTaskInstaller(project: Project) extends ProjectComponent {
Components are deprecated and we're removing them from the plugin in 2020.1
you should be able to directly install this listener in the BSP.xml

2020-02-18 14:01 UTC, jastice commented on bsp/src/org/jetbrains/bsp/BSP.scala
> +    ExternalSystemApiUtil.isExternalSystemAwareModule(BSP.ProjectSystemId.getId, module)
I recently added this same method in BspUtil

2020-02-18 14:01 UTC, jastice commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchTestEnvironmentTaskProvider.scala
> +        "Could not infer Pants target, please choose one from the list",
Is this code specific to Pants? I think the text could be more general

2020-02-18 14:01 UTC, jastice commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchTestEnvironmentTaskProvider.scala
> +    val report = new BuildToolWindowReporter(project = project, buildId = bspTaskId, title = "bsp fetch sources")
The message sounds a bit misleading

2020-02-18 14:01 UTC, jastice commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchTestEnvironmentTaskProvider.scala
> +    val report = new BuildToolWindowReporter(project, bspTaskId, "bsp build")
message doesn't look accurate :)

2020-02-18 14:01 UTC, jastice commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchTestEnvironmentTaskProvider.scala
> +  private def getBspTargets(module: Module): Option[Seq[BuildTargetIdentifier]] =
we can reuse org.jetbrains.bsp.data.BspMetadata#get for most of this

2020-02-18 14:01 UTC, jastice commented on scala/scala-impl/resources/META-INF/scala-plugin-common.xml
> +      <java.programPatcher implementation="org.jetbrains.bsp.project.test.environment.BspProgramPatcher"/>
these should be part of BSP.xml

2020-02-18 14:01 UTC, jastice commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchTestEnvironmentTaskProvider.scala
> +    ).future, 300.millis).getItems
may fail if the server first needs to initialize something or blocks for a while for some other reason, since there is no retry happening here

2020-02-18 14:01 UTC, jastice commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchEnvironmentTaskInstaller.scala
> +          if (BspTesting.isBspRunnerSupportedConfiguration(runConfiguration)) {
should also account for if the server supports `jvmTestEnvironment` request at all

2020-02-18 14:01 UTC, jastice commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchEnvironmentTaskInstaller.scala
> +            beforeRunTasks.add(task)
Instead of adding it before run, could we just get and save the data on project import?

2020-02-24 08:05 UTC, tpasternak commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchEnvironmentTaskInstaller.scala
> +            beforeRunTasks.add(task)
Hi, it was already discussed here https://github.com/build-server-protocol/build-server-protocol/pull/107#discussion_r375338681 It seems it wouldn't be the right approach, as the classpath may change between compilations.

2020-02-24 16:30 UTC, tpasternak commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchTestEnvironmentTaskProvider.scala
> +    ).future, 300.millis).getItems
So what would you recommend here? Increase timeout, do a fixed number retries, or do cancellable retries? 

If cancellable, what would be best the way to trigger cancellation then?

2020-02-25 09:58 UTC, jastice commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchTestEnvironmentTaskProvider.scala
> +    ).future, 300.millis).getItems
At the other places I use `org.jetbrains.bsp.protocol.BspJob#waitForJobCancelable`. Maybe it needs a small adaption for when there is no indicator available.

2020-02-25 16:55 UTC, tpasternak commented on bsp/src/org/jetbrains/bsp/BSP.scala
> +    ExternalSystemApiUtil.isExternalSystemAwareModule(BSP.ProjectSystemId.getId, module)
Done

2020-02-25 16:55 UTC, tpasternak commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchTestEnvironmentTaskProvider.scala
> +        "Could not infer Pants target, please choose one from the list",
Done

2020-02-25 16:55 UTC, tpasternak commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchTestEnvironmentTaskProvider.scala
> +  private def getBspTargets(module: Module): Option[Seq[BuildTargetIdentifier]] =
Done

2020-02-25 16:56 UTC, tpasternak commented on scala/scala-impl/resources/META-INF/scala-plugin-common.xml
> +      <java.programPatcher implementation="org.jetbrains.bsp.project.test.environment.BspProgramPatcher"/>
Done

2020-02-25 16:56 UTC, tpasternak commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchEnvironmentTaskInstaller.scala
> +          if (BspTesting.isBspRunnerSupportedConfiguration(runConfiguration)) {
After some changes, the server capability is checked right before the execution

2020-02-25 16:56 UTC, tpasternak commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchEnvironmentTaskInstaller.scala
> +          if (BspTesting.isBspRunnerSupportedConfiguration(runConfiguration)) {
After some changes, the server capability is checked right before the execution

2020-02-28 15:05 UTC, jastice requested changes
Thanks! Looks like mostly just the strings need to be moved to the bundle. There's a convenient quickfix for that if you didn't notice. And otherwise the listener doesn't need a service to install it.

2020-02-28 15:05 UTC, jastice commented on bsp/resources/META-INF/BSP.xml
> +        <projectService serviceImplementation="org.jetbrains.bsp.project.test.environment.BspFetchEnvironmentTaskInstaller"/>
Doesn't need to be a service at all as no state is maintained. Can be registered as a listener directly something like
```
    <projectListeners>
        <listener class="org.jetbrains.bsp.project.test.environment.BspFetchEnvironmentTask"
                  topic="com.intellij.execution.RunManagerListener" />
    </projectListeners>
```

2020-02-28 15:05 UTC, jastice commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchTestEnvironmentTaskProvider.scala
> +  val msg = "Build Server does not support 'buildTarget/jvmTestEnvironment' endpoint"
should be moved to bundle

2020-02-28 15:05 UTC, jastice commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchTestEnvironmentTaskProvider.scala
> +  override def getName: String = "Use BSP environment"
string should be moved to bundle

2020-02-28 15:05 UTC, jastice commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchTestEnvironmentTaskProvider.scala
> +        "Choose pants target",
should only reference pants if code only appears in pants integration

2020-02-28 15:05 UTC, jastice commented on scala/scala-impl/resources/META-INF/scala-plugin-common.xml
> +      <stepsBeforeRunProvider implementation="org.jetbrains.bsp.project.test.environment.BspFetchTestEnvironmentTaskProvider"/>
should be in BSP.xml

2020-02-28 15:05 UTC, jastice commented on scala/scala-impl/resources/META-INF/scala-plugin-common.xml
> -    <applicationListeners>
undo unindent :)

2020-02-28 15:05 UTC, jastice commented on bsp/src/org/jetbrains/bsp/project/test/environment/BspFetchTestEnvironmentTaskProvider.scala
> +              .getOrElse(Left(BspGetEnvironmentError("Failed to fetch test JVM environment")))
and all these strings should be moved to bundle if they are potentially user-facing

2020-03-02 15:45 UTC, jastice approved these changes
Thanks for the updates! I think it's ready to be merged!

2020-03-06 10:28 UTC, jastice commented
Manually merged after rebase and some changes.
https://github.com/JetBrains/intellij-scala/commit/b30f1712c2bc3182d8c00a05eacf056724a6f55a

2020-03-06 10:28 UTC, closed without merging