Changed getCanonicalPath to custom toCanonicalPath
JetBrains/intellij-scala pull request #624
Opened 2022-07-11 12:24 UTC by mikkoziel

Using method getCanonicalPath was very aggravating for CPU and made imports last longer. I added custom toCanonicalPath implicit method that only take AbsolutePath and normalize it which I think is enough and which makes imports faster(for example: before change - ca.11min, after change- ca.3min)

2022-07-11 18:18 UTC, jastice requested changes
Thank you very much, great find!
I just worry that `toCanonicalPath` is too easily confused with `getCanonicalPath`, maybe we can find another name?

Also, can you please rebase on `idea222.x`, we'll then cherrypick to lower versions as needed.

2022-07-12 12:13 UTC, mikkoziel commented
Changed name to getCanonicalPathSimplified and added comment

2022-07-12 12:26 UTC, mikkoziel commented
I rebased the commit. All should be all right now.
And we will need the cherrypick to version idea221.x.

2022-07-12 13:48 UTC, jastice approved these changes
Thanks!

2022-07-20 12:25 UTC, jastice commented
rebased and merged:
- v221.x: dba55790304b00723b61a3c39e09ceb02f0ae725
- v222.x: 2b10cef3be2c6fd4a4805d2c1f6c7700344af8e2

2022-07-20 12:25 UTC, closed without merging